-- جدول المستخدمين (موجود مسبقاً، للتذكير)
-- create table if not exists public.users (
--   id bigint generated by default as identity primary key,
--   office_name text,
--   phone text unique,
--   password_hash text,
--   security_question text,
--   security_answer text,
--   created_at timestamp with time zone default timezone('utc'::text, now())
-- );

-- جدول المصروفات (الجديد)
create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade not null,
  title text not null,
  amount numeric not null,
  bank text not null,
  date bigint not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- تفعيل الأمان (اختياري حسب إعداداتك)
alter table public.expenses enable row level security;

-- سياسة السماح للجميع (أو يمكنك تخصيصها)
create policy "Enable all access for now" on public.expenses for all using (true);
