-- إنشاء جدول المعاملات (Transactions)
-- الحقول مستخرجة بدقة من TransactionsPage.tsx

CREATE TABLE IF NOT EXISTS "public"."transactions" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL, -- للربط بجدول المستخدمين (Custom Auth)
    "serial_no" TEXT,
    "type" TEXT,
    "client_price" TEXT,
    "agent_price" TEXT,
    "agent" TEXT,
    "client_name" TEXT,
    "duration" TEXT,
    "payment_method" TEXT,
    "created_at" BIGINT, -- تخزين التاريخ كرقم (Timestamp) كما في الكود
    "target_date" BIGINT, -- تخزين التاريخ كرقم (Timestamp)
    "status" TEXT,
    "agent_paid" BOOLEAN DEFAULT FALSE,
    "client_refunded" BOOLEAN DEFAULT FALSE
);

-- تفعيل نظام الحماية (Row Level Security)
ALTER TABLE "public"."transactions" ENABLE ROW LEVEL SECURITY;

-- حذف السياسات القديمة إن وجدت لتجنب التعارض
DROP POLICY IF EXISTS "Enable insert for app" ON "public"."transactions";
DROP POLICY IF EXISTS "Enable select for app" ON "public"."transactions";
DROP POLICY IF EXISTS "Enable delete for app" ON "public"."transactions";
DROP POLICY IF EXISTS "Enable update for app" ON "public"."transactions";

-- إنشاء سياسات تسمح للموقع بالكتابة والقراءة (نسخة من سياسات المصروفات)
-- هذه السياسات تسمح بالإضافة والتعديل للعامة (Anon) لأننا نتحقق من user_id في الكود
CREATE POLICY "Enable insert for app" ON "public"."transactions"
FOR INSERT TO anon, authenticated WITH CHECK (true);

CREATE POLICY "Enable select for app" ON "public"."transactions"
FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "Enable delete for app" ON "public"."transactions"
FOR DELETE TO anon, authenticated USING (true);

CREATE POLICY "Enable update for app" ON "public"."transactions"
FOR UPDATE TO anon, authenticated USING (true);
