-- 1. إنشاء جدول الحسابات (Accounts)
CREATE TABLE IF NOT EXISTS "public"."accounts" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL,
    "bank_name" TEXT NOT NULL,
    "balance" NUMERIC DEFAULT 0,
    "pending_balance" NUMERIC DEFAULT 0,
    "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. إضافة قيد لضمان عدم تكرار اسم البنك لنفس المستخدم (Unique Constraint)
ALTER TABLE "public"."accounts" 
ADD CONSTRAINT "accounts_user_bank_unique" UNIQUE ("user_id", "bank_name");

-- 3. تفعيل نظام الحماية (RLS)
ALTER TABLE "public"."accounts" ENABLE ROW LEVEL SECURITY;

-- 4. حذف السياسات القديمة (إن وجدت) لتجنب التعارض
DROP POLICY IF EXISTS "Enable insert for app" ON "public"."accounts";
DROP POLICY IF EXISTS "Enable select for app" ON "public"."accounts";
DROP POLICY IF EXISTS "Enable update for app" ON "public"."accounts";
DROP POLICY IF EXISTS "Enable delete for app" ON "public"."accounts";

-- 5. إنشاء سياسات الأمان (نسخة طبق الأصل من Expenses/Agents)
-- السماح بالإضافة (Insert)
CREATE POLICY "Enable insert for app" ON "public"."accounts"
FOR INSERT TO anon, authenticated WITH CHECK (true);

-- السماح بالعرض (Select) - سيقوم الكود بالفلترة حسب user_id
CREATE POLICY "Enable select for app" ON "public"."accounts"
FOR SELECT TO anon, authenticated USING (true);

-- السماح بالتعديل (Update) - لتحديث الأرصدة
CREATE POLICY "Enable update for app" ON "public"."accounts"
FOR UPDATE TO anon, authenticated USING (true);

-- السماح بالحذف (Delete) - لتصفير الخزينة
CREATE POLICY "Enable delete for app" ON "public"."accounts"
FOR DELETE TO anon, authenticated USING (true);
