-- 1. حذف الجدول القديم (إن وجد) لضمان تطابق الهيكل
DROP TABLE IF EXISTS "public"."agents";

-- 2. إنشاء الجدول بنفس هيكلية المصروفات (مع تعديل الحقول لتناسب المعقبين)
CREATE TABLE "public"."agents" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL, -- للربط بنظام الدخول المخصص
    "name" TEXT NOT NULL,
    "phone" TEXT,
    "whatsapp" TEXT,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. تفعيل نظام الحماية RLS
ALTER TABLE "public"."agents" ENABLE ROW LEVEL SECURITY;

-- 4. تطبيق السياسات المفتوحة (نسخة طبق الأصل من المصروفات)
-- سياسة السماح بالإضافة للجميع (الموقع يتولى تحديد user_id)
CREATE POLICY "Allow insert for public" ON "public"."agents"
FOR INSERT TO public WITH CHECK (true);

-- سياسة السماح بالعرض للجميع (الكود يقوم بالفلترة حسب user_id)
CREATE POLICY "Allow select for public" ON "public"."agents"
FOR SELECT TO public USING (true);

-- سياسة السماح بالحذف للجميع
CREATE POLICY "Allow delete for public" ON "public"."agents"
FOR DELETE TO public USING (true);

-- سياسة السماح بالتعديل (Update)
CREATE POLICY "Allow update for public" ON "public"."agents"
FOR UPDATE TO public USING (true);
