-- إصلاح جدول المعقبين وصلاحيات الإضافة من الموقع

-- 1. التأكد من أن الجدول موجود وبالأنواع الصحيحة (BIGINT لـ user_id)
CREATE TABLE IF NOT EXISTS "public"."agents" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL, -- ضروري جداً أن يكون BIGINT ليتوافق مع نظام الدخول
    "name" TEXT NOT NULL,
    "phone" TEXT,
    "whatsapp" TEXT,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. تفعيل نظام الحماية
ALTER TABLE "public"."agents" ENABLE ROW LEVEL SECURITY;

-- 3. حذف أي سياسات قديمة قد تسبب تعارضاً
DROP POLICY IF EXISTS "Enable insert for app" ON "public"."agents";
DROP POLICY IF EXISTS "Enable select for app" ON "public"."agents";
DROP POLICY IF EXISTS "Enable delete for app" ON "public"."agents";
DROP POLICY IF EXISTS "Enable update for app" ON "public"."agents";

-- 4. إنشاء سياسات تسمح للموقع (Anon/Authenticated) بالإضافة والقراءة
-- التطبيق يتحقق من هوية المستخدم برمجياً، لذا نسمح هنا بالمرور
CREATE POLICY "Enable insert for app" ON "public"."agents"
FOR INSERT TO anon, authenticated WITH CHECK (true);

CREATE POLICY "Enable select for app" ON "public"."agents"
FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "Enable delete for app" ON "public"."agents"
FOR DELETE TO anon, authenticated USING (true);

CREATE POLICY "Enable update for app" ON "public"."agents"
FOR UPDATE TO anon, authenticated USING (true);
