-- Create subscription_requests table for unified admin view
CREATE TABLE IF NOT EXISTS subscription_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    user_name TEXT,
    phone TEXT,
    duration TEXT,
    bank TEXT,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE subscription_requests ENABLE ROW LEVEL SECURITY;

-- Policy: Allow users to insert their own requests
CREATE POLICY "Users can insert own requests" ON subscription_requests
    FOR INSERT WITH CHECK (true);

-- Policy: Allow admins/golden to view all (simplified for this app structure)
CREATE POLICY "Admins can view all requests" ON subscription_requests
    FOR SELECT USING (true);

-- Policy: Allow updates (approve/reject)
CREATE POLICY "Admins can update requests" ON subscription_requests
    FOR UPDATE USING (true);

-- Policy: Allow deletes
CREATE POLICY "Admins can delete requests" ON subscription_requests
    FOR DELETE USING (true);
