-- Create the expenses table
CREATE TABLE IF NOT EXISTS public.expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID DEFAULT auth.uid(), -- Automatically link to the authenticated user
    title TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    bank TEXT NOT NULL,
    date BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;

-- Policy 1: Allow authenticated users to insert their own expenses
CREATE POLICY "Enable insert for authenticated users only"
ON public.expenses
FOR INSERT
TO authenticated
WITH CHECK (true); 
-- Note: In a strict setup, we would enforce (auth.uid() = user_id) in the CHECK

-- Policy 2: Allow users to view only their own expenses
CREATE POLICY "Enable read access for owning user"
ON public.expenses
FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

-- Optional: Grant permissions to authenticated role if needed
GRANT ALL ON TABLE public.expenses TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE expenses_id_seq TO authenticated;
