-- إصلاح خطأ تعارض البيانات (Fix Type Mismatch Error)
-- المشكلة السابقة: محاولة مقارنة UUID (من نظام Supabase) مع BIGINT (من نظامنا المخصص).
-- الحل: ربط جدول المصروفات بجدول users العام (public.users) مباشرة.

-- 1. حذف الجدول القديم إذا وجد لتجنب التعارض
DROP TABLE IF EXISTS expenses;

-- 2. إنشاء جدول المصروفات بالمواصفات الصحيحة
CREATE TABLE expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE, -- ربط صحيح بجدول المستخدمين لدينا
  title TEXT NOT NULL,
  amount DECIMAL NOT NULL,
  bank TEXT NOT NULL,
  date BIGINT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. تفعيل نظام الحماية
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;

-- 4. إضافة سياسات الأمان (Policies) المتوافقة مع النظام المخصص
-- السماح بالإضافة للجميع (سيتم التحكم في user_id من التطبيق)
CREATE POLICY "Allow insert for app users" ON expenses
FOR INSERT WITH CHECK (true);

-- السماح بالعرض (التطبيق سيقوم بفلترة البيانات حسب المستخدم المسجل)
CREATE POLICY "Allow select for app users" ON expenses
FOR SELECT USING (true);

-- السماح بالحذف
CREATE POLICY "Allow delete for app users" ON expenses
FOR DELETE USING (true);
