-- إنشاء جدول العملاء (Clients)
-- الحقول مستخرجة من واجهة التطبيق: الاسم، الجوال، الواتساب
CREATE TABLE IF NOT EXISTS "public"."clients" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL, -- لربط العميل بالمستخدم المسجل
    "name" TEXT NOT NULL,
    "phone" TEXT,
    "whatsapp" TEXT,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- تفعيل نظام الحماية (RLS)
ALTER TABLE "public"."clients" ENABLE ROW LEVEL SECURITY;

-- تنظيف السياسات القديمة إن وجدت
DROP POLICY IF EXISTS "Enable insert for app" ON "public"."clients";
DROP POLICY IF EXISTS "Enable select for app" ON "public"."clients";
DROP POLICY IF EXISTS "Enable delete for app" ON "public"."clients";

-- تطبيق نفس سياسات المصروفات والمعقبين (لضمان عمل نظام الدخول المخصص)
-- يسمح للتطبيق بالإضافة والقراءة والحذف، بينما يتم تصفية البيانات برمجياً حسب user_id
CREATE POLICY "Enable insert for app" ON "public"."clients"
FOR INSERT TO anon, authenticated WITH CHECK (true);

CREATE POLICY "Enable select for app" ON "public"."clients"
FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "Enable delete for app" ON "public"."clients"
FOR DELETE TO anon, authenticated USING (true);
