-- 1. Create the agents table with BIGINT user_id to match your custom auth system
CREATE TABLE IF NOT EXISTS "public"."agents" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL, -- Links to public.users.id
    "name" TEXT NOT NULL,
    "phone" TEXT,
    "whatsapp" TEXT,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE "public"."agents" ENABLE ROW LEVEL SECURITY;

-- 3. Clean up any existing policies to avoid conflicts
DROP POLICY IF EXISTS "Enable insert for app" ON "public"."agents";
DROP POLICY IF EXISTS "Enable select for app" ON "public"."agents";
DROP POLICY IF EXISTS "Enable delete for app" ON "public"."agents";

-- 4. Create Permissive Policies for Custom Auth (Replicating Expenses Policies)
-- Since the app handles user_id filtering in the query, we allow access to the anon key.

-- Allow Insert
CREATE POLICY "Enable insert for app" ON "public"."agents"
FOR INSERT TO anon, authenticated WITH CHECK (true);

-- Allow Select
CREATE POLICY "Enable select for app" ON "public"."agents"
FOR SELECT TO anon, authenticated USING (true);

-- Allow Delete
CREATE POLICY "Enable delete for app" ON "public"."agents"
FOR DELETE TO anon, authenticated USING (true);

-- 5. Optional: Create an index on user_id for faster filtering
CREATE INDEX IF NOT EXISTS agents_user_id_idx ON "public"."agents" ("user_id");
