-- جدول تحويلات المعقبين (Agent Transfers)
CREATE TABLE IF NOT EXISTS public.agent_transfers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT, -- لربط السجل بالمستخدم
    agent_name TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    bank TEXT NOT NULL,
    date BIGINT NOT NULL, -- تخزين التاريخ كرقم (Timestamp) ليتوافق مع الكود
    transaction_count INTEGER DEFAULT 0,
    created_by TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- تفعيل الحماية (RLS)
ALTER TABLE public.agent_transfers ENABLE ROW LEVEL SECURITY;

-- سياسة السماح للجميع (مؤقتاً لتوافق النظام الحالي)
CREATE POLICY "Enable read/write for all users" ON public.agent_transfers
    FOR ALL USING (true) WITH CHECK (true);

-- جدول مرتجع العملاء (Client Refunds) - لإكمال كشف الحساب
CREATE TABLE IF NOT EXISTS public.client_refunds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    client_name TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    bank TEXT NOT NULL,
    date BIGINT NOT NULL,
    transaction_count INTEGER DEFAULT 0,
    created_by TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- تفعيل الحماية (RLS)
ALTER TABLE public.client_refunds ENABLE ROW LEVEL SECURITY;

-- سياسة السماح للجميع
CREATE POLICY "Enable read/write for all users" ON public.client_refunds
    FOR ALL USING (true) WITH CHECK (true);
